version: '3.7'

x-app: &app
  build:
    context: .
    dockerfile: ./.dockerdev/Dockerfile
    args:
      pg_major: '13'
      node_major: '10'
      node_version: ${NODE_PACKAGE_VERSION:-10.23.2}
      yarn_version: '1.16.0'
      bundler_version: '2.3.1'
      gem_home: /bundle
  environment: &env
    NODE_ENV: development
    WEBPACKER_DEV_SERVER_HOST: webpacker
  environment: &pg-env
    POSTGRES_DB: ${DATABASE_NAME:-app}
    POSTGRES_USER: ${DATABASE_USERNAME:-app}
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-app}
    PGUSER: ${DATABASE_USERNAME:-app}
    PGPASSWORD: ${DATABASE_PASSWORD:-app}
    PGDATABASE: ${DATABASE_NAME:-app}
    PGPORT: ${DATABASE_PORT:-5432}
  image: media-gallery:1.0.0
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
    - .dockerdev/.psqlrc:/root/.psqlrc:ro
  environment:
    <<: *env
    <<: *pg-env
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_USERNAME: ${DATABASE_USERNAME:-app}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD:-app}
    DATABASE_NAME: ${DATABASE_NAME:-app}
    REDIS_URL: redis://redis:6379/
    ELASTICSEARCH_HOST: ${ELASTICSEARCH_HOST:-elasticsearch}
    BOOTSNAP_CACHE_DIR: /bundle/bootsnap
    HISTFILE: /app/log/.bash_history
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
    EDITOR: nano
    SIDEKIQ_LOG_TO_STDOUT: "true"
    RAILS_LOG_TO_STDOUT: "true"
  depends_on:
    - postgres
    - redis

services:
  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - '3001:3001'

  rails:
    <<: *backend
    entrypoint: /app/docker-compose-entrypoint.sh
    command: [ 'rails', 'server', '-b', '0.0.0.0', '-p', '3000']
    ports:
      - '${RAILS_PORT:-3000}:3000'

  postgres:
    image: ${POSTGRES_IMAGE:-postgres}:${POSTGRES_VERSION:-13.2-alpine}
    volumes:
      - .dockerdev/.psqlrc:/root/.psqlrc:ro
      - postgres:${PGDATA:-/var/lib/postgresql/data}
      - ./db/dumps:/docker-entrypoint-initdb.d/dumps
      - ./log:/root/log:cached
    environment:
      <<: *pg-env
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - '${POSTGRES_PORT:-5432}:5432'

  redis:
    image: redis:${REDIS_VERSION:-7.0.4}
    volumes:
      - redis:/data
    ports:
      - '${REDIS_SERVER_PORT:-6379}:6379'

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION:-5.6.4}
    command:
      - "bin/elasticsearch"
      - "-Expack.security.enabled=false"
      - "-Ediscovery.type=single-node"
      - "-Ebootstrap.memory_lock=true"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - '${ELASTICSEARCH_PORT:-9200}:9200'

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - '${WEBPACK_DEV_SERVER_PORT:-3035}:3035'
      - '${WEBPACK_BUNDLE_ANALYZER_PORT:-8888}:8888'
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
      - packs:/app/public/packs
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACK_BUNDLE_ANALYZER_HOST: 0.0.0.0

volumes:
  postgres:
  redis:
  bundle:
  node_modules:
  rails_cache:
  packs:
