export_i18n_js: true
translations:
  - file: app/javascript/admin/common/translations.js
    only:
      - en.activerecord.*
      - ru.activerecord.*
      - ru.errors.*
      - en.admin.*
      - ru.admin.*
