export_i18n_js: false
translations:
  - file: app/javascript/admin/common/translations.js
    only:
      - en.activerecord.*
      - ru.activerecord.*
      - ru.errors.*
      - en.admin.*
      - ru.admin.*
      - en.responders.*
      - ru.responders.*
