default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false
  webpack_compile_output: false
  resolved_paths: ['.', 'app/javascript/src', 'app/themes']
  cache_manifest: false
  extract_css: true
  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .svg
    - .gif
    - .ico
    - .tiff
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2
    - .mp4
    - .webm
  extensions:
    - .js
    - .jsx
    - .coffee
    - .cjsx
    - .ts
    - .vue
    - .sass
    - .scss
    - .css
    - .slim
    - .erb
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: false
  dev_server:
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: false
    inline: true
    overlay: true
    compress: true
    disable_host_check: true
    use_local_ip: false
    quiet: false
    headers:
      'Access-Control-Allow-Origin': '*'
    watch_options:
      ignored: '**/node_modules/**'

test:
  <<: *default
  compile: true
  public_output_path: packs-test

staging:
  <<: *default
  compile: false
  cache_manifest: true

preprod:
  <<: *default
  compile: false
  cache_manifest: true

production:
  <<: *default
  compile: false
  cache_manifest: true
